=== kblin/mibig-ui-datastructures/schema/basic_data.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$schema_created": "2022-03-07T11:11:15+01:00",
    "$schema_version": "1.0",
    "$id": "https://mibig.secondarymetabolites.org/schemas/basis_data.json",
    "title": "Basic MIBiG entry information",
    "description": "The basic set of information required for a minimal MIBiG entry",
    "additionalProperties": false,
    "properties": {
        "accession": {
            "type": "string"
        },
        "biosynthetic_classes": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "compounds": {
            "items": {
                "$ref": "https://mibig.secondarymetabolites.org/schemas/compound.json"
            },
            "type": "array"
        },
        "locus": {
            "$ref": "https://mibig.secondarymetabolites.org/schemas/locus.json"
        },
        "organism_name": {
            "type": "string"
        },
        "ncbi_taxid": {
            "type": "integer"
        },
        "publications": {
            "items": {
                "$ref": "https://mibig.secondarymetabolites.org/schemas/db_xref.json"
            },
            "type": "array"
        },
        "status": {
            "type": "string"
        }
    },
    "required": [
        "accession",
        "biosynthetic_classes",
        "compounds",
        "locus",
        "ncbi_taxid",
        "organism_name",
        "publications"
    ]
}

=== kblin/mibig-ui-datastructures/examples/basic_data.json
{
    "accession": "BGC0001070",
    "biosynthetic_classes": [
        "NRP",
        "Polyketide"
    ],
    "compounds": [
        {
            "activities": [
                "antibacterial"
            ],
            "structure": "CC[C@H](C(=O)NC/C=C/C=C(\\C)/[C@H]([C@@H](C)[C@H]1[C@H]([C@H]([C@H](O1)/C=C/C=C/C=C(\\C)/C(=C\\2/C(=O)C=CNC2=O)/O)O)O)OC)[C@@]3([C@@H]([C@@H](C([C@@H](O3)/C=C/C=C\\C)(C)C)O)O)O",
            "synonyms": [
                "mocimycin",
                "delvomycin"
            ],
            "targets": [
                {
                    "name": "EG-Tu"
                }
            ],
            "name": "kirromycin",
            "database_ids": [
                {
                    "database": "pubchem",
                    "identifier": "54697674"
                },
                {
                    "database": "chemspider",
                    "identifier": "4883396"
                }
            ],
            "molecular_mass": 796.4146253600001,
            "molecular_formula": "C43H60N2O12"
        }
    ],
    "locus": {
        "accession": {
            "database": "genbank",
            "identifier": "AM746336.1"
        },
        "completeness": "complete",
        "evidences": [
            "knock-out studies"
        ]
    },
    "ncbi_taxid": 1214242,
    "organism_name": "Streptomyces collinus Tu 365",
    "publications": [
        "pubmed:4554808",
        "pubmed:4373734",
        "pubmed:18291322",
        "pubmed:21513880",
        "pubmed:19609288",
        "pubmed:21401713",
        "pubmed:23828654"
    ]
}
