=== kblin/mibig-ui-datastructures/schema/compound.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$schema_created": "2022-03-07T11:45:13+01:00",
    "$schema_version": "1.0",
    "$id": "https://mibig.secondarymetabolites.org/schemas/compound.json",
    "title": "Compound",
    "description": "All we need to know about a MIBiG compound",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "activities": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "moieties": {
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "subcluster": {
                        "items": {
                            "type": "string"
                        },
                        "type": "array"
                    }
                },
                "required": ["name"]
            },
            "type": "array"
        },
        "structure": {
            "type": "string"
        },
        "synonyms": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "targets": {
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "publications": {
                        "items": {
                            "$ref": "https://mibig.secondarymetabolites.org/schemas/db_xref.json"
                        },
                        "type": "array"
                    }
                }
            },
            "type": "array"
        },
        "database_ids": {
            "description": "Entries for this compound in compound databases",
            "items": {
                "$ref": "https://mibig.secondarymetabolites.org/schemas/db_xref.json"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        },
        "evidences": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "mass_spec_ion_type": {
            "type": "string"
        },
        "molecular_mass": {
            "type": "number",
            "minimum": 0
        },
        "molecular_formula": {
            "type": "string"
        }
    },
    "required": ["name"]
}

=== kblin/mibig-ui-datastructures/examples/compound.json
{
    "activities": ["antibacterial"],
    "structure": "CC[C@H](C(=O)NC/C=C/C=C(\\C)/[C@H]([C@@H](C)[C@H]1[C@H]([C@H]([C@H](O1)/C=C/C=C/C=C(\\C)/C(=C\\2/C(=O)C=CNC2=O)/O)O)O)OC)[C@@]3([C@@H]([C@@H](C([C@@H](O3)/C=C/C=C\\C)(C)C)O)O)O",
    "synonyms": ["mocimycin", "delvomycin"],
    "targets": [{"name": "EG-Tu"}],
    "name": "kirromycin",
    "database_ids": [
        {"database": "pubchem", "identifier": "54697674"},
        {"database": "chemspider", "identifier": "4883396"}
    ],
    "molecular_mass": 796.4146253600001,
    "molecular_formula": "C43H60N2O12"
}
